import type { Metadata } from 'next'
import './globals.css'
import { ViewTransitions } from 'next-view-transitions'

// Fuentes
import { oswald, merriweather } from '@/fonts'

import { ScrollLayout } from '@/layouts/ScrollLayout'
import { ScrollTop } from '@/components/ScrollTop'
import { MagneticButton } from '@/components/MagneticButton'
import { Footer } from '@/components/footer/footer'
import { Header } from '@/components/header/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang='en'>
        <ScrollTop />
        <body
          className={`${oswald.variable} ${merriweather.variable} antialiased`}
        >
          <ScrollLayout>
            <Header />
            <main className='min-h-[100dvh]'>
              {children}
              <MagneticButton size='sm' />
            </main>
            <Footer />
          </ScrollLayout>
        </body>
      </html>
    </ViewTransitions>
  )
}
